---
title: "Style Guide"
date: "`r Sys.Date()`"
scctemplate:
  header:
    site_branding: "Suffolk County Council"
  navigation:
    breadcrumb_trail:
      - href: "index.html"
        text: "Home"
      - text: "Style Guide"
    toc:
      sticky: false
      numbered: false
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

## Suffolk County Council brand and styling

The font and colour codes have been sourced from the [Suffolk County Council's website](https://www.suffolk.gov.uk/), and Google Chrome's Inspect functionality (Ctrl + Shift + i).

The style can be called to any ggplot2 object using `scc_style()`

```{r style_example, warning = FALSE, message = FALSE}
library(ggplot2)
library(gapminder)
library(dplyr)
library(sccthemes)

barchart_data <- gapminder |> 
  filter(year == 2007 & continent == "Europe") |> 
  arrange(desc(gdpPercap)) |> 
  head(5)

barchart_data |> 
  ggplot(aes(x = country, y = gdpPercap)) +
  geom_bar(
    stat = "identity",
    position = "identity",
    color = "#333333",
    fill = "#428bca"
  ) +
  geom_hline(
    yintercept =  0,
    size = 1,
    colour = "#333333"
  ) +
  scc_style() +
  labs(
    title = "Europe's Richest Countries",
    subtitle = "GDP per Capita, 2007"
  )
```
